//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storege()
        {
            this.Count = 0;
        }
    
        public int Id { get; set; }
        public int Count { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual Product Product { get; set; }
    }
}
